server:
  port: 8080
  servlet:
    context-path: /api
    
jwt:
  secret: A0B1C2D3E4F5G6H7I8J9KALBMCNDOEPFQ0R1S2T3U4V5W6X7Y8Z9
  expire: 10080
  prefix: "Bearer"

spring:
  datasource:
    url: jdbc:mysql://120.92.106.105:3306/admin?characterEncoding=UTF-8
    username: admin
    password: admin1234
    
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql    